- name: MongoDB is running
  docker_container:
    restart_policy: always
    name: mongodb
    image: mongo:latest
    ports: 
    - "27017:27017"
    privileged: yes
    env:
#      MONGODB_USERNAME: ude
#      MONGODB_PASSWORD: ude
      MONGODB_DATABASE: ec
    volumes:
      - /data/mongodb:/data/db
  when: not skip_ui is defined
  tags: [mongodb]
